sudo: required
services:
  - docker

before_install:
  - docker build -t rishu53/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true rishu53/frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker_test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-823931889189"
  bucket_path: "DockerTest"
  on:
    branch: master
  access_key_id: $KEY
  secret_access_key: $PASSWORD